"""fresh migration

Revision ID: 3b7f6cac8ce6
Revises: 
Create Date: 2025-05-25 03:41:50.528939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7f6cac8ce6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('pelanggaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.Column('plat_nomor', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gambar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_file', sa.String(length=100), nullable=False),
    sa.Column('tipe', sa.String(length=30), nullable=True),
    sa.Column('resolusi', sa.String(length=20), nullable=True),
    sa.Column('ukuran_byte', sa.Integer(), nullable=True),
    sa.Column('ukuran_terenkripsi', sa.Integer(), nullable=True),
    sa.Column('pelanggaran_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pelanggaran_id'], ['pelanggaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keamanan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.String(length=100), nullable=True),
    sa.Column('poly1305_tag', sa.String(length=100), nullable=True),
    sa.Column('poly1305_valid', sa.Boolean(), nullable=True),
    sa.Column('encrypt_time_ms', sa.Float(), nullable=True),
    sa.Column('decrypt_time_ms', sa.Float(), nullable=True),
    sa.Column('total_process_ms', sa.Float(), nullable=True),
    sa.Column('ciphertext_len', sa.Integer(), nullable=True),
    sa.Column('gambar_valid', sa.Boolean(), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('pelanggaran_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pelanggaran_id'], ['pelanggaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keamanan')
    op.drop_table('gambar')
    op.drop_table('pelanggaran')
    op.drop_table('device')
    # ### end Alembic commands ###
